CREATE TABLE If NOT Exists club(
     row_id INT(11) NOT NULL,
     club_id INT(11) NOT NULL AUTO_INCREMENT,
     club_name INT(11) NOT NULL,
     club_description TEXT NOT NULL,
     club_founded_date VARCHAR(30),
     club_address VARCHAR(50),
     club_email VARCHAR(30),
     club_division INT(11) NOT NULL,
     club_affiliation INT(11) NOT NULL,
     home_jersey_color VARCHAR(30) NOT NULL,
     away_jersey_color VARCHAR(30) NOT NULL,
     club_sponsor VARCHAR(30),
     kit_brand INT(11) NOT NULL, 
     club_logo VARCHAR(30),
     createdDate date NOT NULL DEFAULT CURRENT_TIMESTAMP,
     createdBy VARCHAR(30),
     modifiedDate date DEFAULT CURRENT_TIMESTAMP, 
     modifiedBy VARCHAR(30),
     isDeleted VARCHAR(30),
     UNIQUE (row_id),
     PRIMARY KEY (club_id),
     FOREIGN KEY (club_name) REFERENCES category_value(cvalue_id),
     FOREIGN KEY (club_division) REFERENCES category_value(cvalue_id),
     FOREIGN KEY (club_affiliation) REFERENCES category_value(cvalue_id),
     FOREIGN KEY (kit_brand) REFERENCES category_value(cvalue_id)
);