CREATE TABLE If NOT Exists matches(
    row_id INT NOT NULL,
    match_id INT(128) NOT NULL AUTO_INCREMENT,
    tournament_id INT(128), 
    club_1 INT(11), 
    club_2 INT(11), 
    matchDate VARCHAR(30) NOT NULL,
    KickOffTime time(6),
    club_1_score INT(128) NOT NULl,
    club_2_score INT(128) NOT NULl,
    club_1_result VARCHAR(256) NOT NULL,
    club_2_result VARCHAR(256) NOT NULL,
    match_status INT(11) NOT NULL,
    UNIQUE (row_id),
    PRIMARY KEY (match_id),
    FOREIGN KEY (tournament_id) REFERENCES tournaments(tournament_id),
    FOREIGN KEY (club_1) REFERENCES category_value(cvalue_id),
    FOREIGN KEY (club_2) REFERENCES category_value(cvalue_id),
    FOREIGN KEY (match_status) REFERENCES category_value(cvalue_id)
