
/* Inserting club detail */
INSERT INTO `club` (`row_id`, `club_id`, `club_name`, `club_description`, `club_founded_date`, `club_address`, `club_email`, `club_division`, `club_affiliation`, `home_jersey_color`, `away_jersey_color`, `club_sponsor`, `kit_brand`, `club_logo`, `createdDate`, `createdBy`, `modifiedDate`, `modifiedBy`, `isDeleted`) VALUES
('1', '1', '125', 'The Armed Police Force Club, commonly known as the APF Club, is a departmental armed police sporting club of Nepal. They currently play in the top division of the country.\r\n', '2001 A.D.', 'Swoyanbhu, Kathmandu', 'computersection@apf.gov.np', '107', '149', 'Grey', 'White', 'Agni Mahindra', '142', 'apf.png', '2019-12-16', 'Admin', 'current_timestamp()', NULL, NULL), 
('2', '2', '126', 'Brigade Boys Club is a Nepalese football club from Lalitpur that was established in 1987, which plays in the town of Kathmandu. They play in the Nepalese first division, the Nepal A- Division League.\r\n\r\n', '', 'Manbhawan, Lalitpur', NULL, '107', '149', 'Red', 'White', '', '142', 'bbc.png', '2019-12-16', 'Admin', 'current_timestamp()', NULL, NULL),
('3', '3', '127', 'Founded in 1981 Chyasal Youth Club was established with a mission, Sports for health and fitness for the community and national pride. They Place in the A divison flight of Neapli A division league.\r\n\r\n', '1981', 'Chyasal, Lalitpur', NULL, '107', '149', 'Green', 'Blue', 'Himalayan College of Management, Grace International', '142', 'cyc.png', '2019-12-16', 'Admin', 'current_timestamp()', NULL, NULL), 
('4', '4', '128', 'Friends Club is situated in Kopundole Lalitpur. This club is known for nurturing young talent of Nepalese Football. Friends Club has produced more than 200 national football players till date. It remained only a football club that every now and then organized certain social activities.\r\n\r\n\r\n', '1972 A.D.', 'Kupondole, Lalitpur', 'friendsclubkopundole@gmail.com', '107', '149', 'Blue', 'Red', 'Nepal Investment Bank Limited', '142', 'fc.png', '2019-12-16', 'Admin', 'current_timestamp()', NULL, NULL), 
('5', '5', '129', 'Himalayan Sherpa Club is a topflight association football club from Nepal.. Himalayan Sherpa Club has won the title of Sindhu Gold Cup, Sayapatri Gold Cup, Butwol and 1st runners up in All Star Cup in Aabu Khaireni.\r\n', NULL, 'Hattigauda, Kathmandu', 'ktsherpa@gmail.com', '107', '149', 'Orange', 'White', 'Yeti Airlines', '142', 'hsc.png', '2019-12-16', 'Admin', 'current_timestamp()', NULL, NULL), 
('6', '6', '130', 'Established in 2029 B.S. Jawalakhel Youth Club is a social organization with focus on Sports and Social services. JYC is also social organization as it has been conducting various activities like Blood Donation, Health Camp, and Environment Awareness Program.\r\n', '1952 A.D.', 'Jawalakhel, Lalitpur', 'info@jyc.com.np', '107', '149', 'White', 'Blue', 'Prabhu Bank', '146', 'jyc.png', '2019-12-16', 'Admin', 'current_timestamp()', NULL, NULL), 
('7', '7', '131', 'Established in 1973, Machhindra FC is a top flight Nepali football team from the central Kathmandu neighborhood of Keltole. The club finished in 6th place in the 2005/06 Martyrs League.\r\n', '1973 A.D.', 'MasanGalli, Kathmandu', 'machhindraclub1973@gmail.com', '107', '149', 'Red', 'White', 'San Miguel, Pepe Pizza', '142', 'mc.png', '2019-12-16', 'Admin', 'current_timestamp()', NULL, NULL), 
('8', '8', '132', 'Manang Marshyangdi Club is based in Swayambhu, Kathmandu. They play in the Nepalese first division, the Nepal A- Division League. They are in top spot for winning National League Championships and hey have won 7 National Leagues Championships Title.\r\n', '1982 A.D.', 'Nayabazar, Kathmandu', 'manangmarshyangdi@gmail.com', '107', '149', 'Sky Blue', 'Green/White', 'Manang Trust', '142', 'mmc.png', '2019-12-16', 'Admin', 'current_timestamp()', NULL, NULL), 
('9', '9', '133', 'Nepal Police Club formerly known as Mahendra Police Club is departmental police football and cricket club of Nepal. They currently play in the top division of the country.\r\n\r\n', '1952 A.D.', 'Maharajgunj, Kathmandu', 'info@nepalpolice.gov.np', '107', '149', 'Red', 'Blue', 'Nepal Telecom', '142', 'npc.png', '2019-12-16', 'Admin', 'current_timestamp()', NULL, NULL), 
('10', '10', '134', 'N.R.T. was established in 1991 BS (1934 AD). It has distinction to be a pioneer in the sport who has camouflaged a football team that mobilized youth against the autocratic Rana regime that ruled for 104 years.\r\n', '1934 A.D.', 'Tripureshwor, Kathmandu', 'kkm@nrt.org.np', '107', '149', 'Green ', 'Red', NULL, '142', 'nrt.png', '2019-12-16', 'Admin', 'current_timestamp()', NULL, '');